version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    commit-message:
      prefix: "prod"
      prefix-development: "dev"
      # include: "scope"
    schedule:
      interval: weekly
