version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    commit-message:
      prefix: ""
      prefix-development: "Dev:"
      include: "scope"
    schedule:
      interval: weekly
