name: RSpec
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install ruby
        uses: ./.github/workflows/rspec_setup

      - name: Run
        run: bundle info business
